name: chasier
description: Biztro cashier program
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  colorful_safe_area: ^0.3.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  esc_pos_bluetooth: ^0.2.8
  esc_pos_utils: ^0.3.6
  fluid_layout: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_bluetooth_basic: ^0.1.5
  flutter_launcher_icons: ^0.8.0
  flutter_ringtone_player: ^3.0.0
  fluttertoast: ^8.0.8
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/logo2.jpg
    - assets/rabbit.jpg
    - assets/alarm.mp3

  fonts:
    - family: Modum
      fonts:
        - asset: fonts/Modum.ttf
    - family: Code New Roman
      fonts:
        - asset: fonts/code new roman.otf
    - family: Renogare
      fonts:
        - asset: fonts/Renogare.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
